name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '27 9 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue. we will close the issue soon. If this issue has not been resolved, please update the issue and contact us in time.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
